analyzer:
  language: 
    strict-casts: true
    strict-inference: true
  exclude:
    # Ignore files that are generated
    - "**.freezed.dart"
    - "**.g.dart"
    # Ignore TwIcons file
    - "**tw_icons.dart"
  errors:
    #argument_type_not_assignable: ignore
    #invalid_assignment: ignore
    invalid_use_of_visible_for_testing_member: ignore
    # For freezed purposes
    invalid_annotation_target: ignore
    for_in_of_invalid_type: ignore
